services:
  database:
    container_name: stockdog_db
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - stockdog

  backend:
    container_name: stockdog_backend
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      CRON_SCHEDULE: ${CRON_SCHEDULE}
      TZ: ${TZ}
      PORT: ${PORT}
    depends_on:
      - database
    networks:
      - stockdog

  grafana:
    container_name: stockdog_grafana
    build:
      context: .
      dockerfile: ./apps/grafana/Dockerfile
    ports:
      - '${GF_PORT}:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - stockdog
    depends_on:
      - database
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

volumes:
  db-data:
  grafana-storage:

networks:
  stockdog:
    name: stockdog_network
