services:
  database:
    container_name: ${SERVICE_NAME}_db
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    container_name: ${SERVICE_NAME}_backend
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      CRON_SCHEDULE: ${CRON_SCHEDULE}
      TZ: ${TZ}
      PORT: ${PORT}
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - database

  dashboard:
    container_name: ${SERVICE_NAME}_dashboard
    build:
      context: .
      dockerfile: ./apps/dashboard/Dockerfile
    ports:
      - '${GF_PORT}:3000'
    volumes:
      - dashboard:/var/lib/grafana
    depends_on:
      - database
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

volumes:
  db-data:
  dashboard:

networks:
  default:
    name: ${SERVICE_NAME}
