# Production stage
FROM node:24-alpine

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

RUN pnpm install --frozen-lockfile --prod

COPY dist/apps/cli ./

ENTRYPOINT ["node", "main.js"]
