name: CI

env:
  NODE_VERSION: 18

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  issues: write
  pull-requests: write

jobs:
  test:
    name: Unit tests & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install test dependencies
        run: yarn install --production=false --only=dev

      - name: Lint code
        run: yarn lint

      - name: Run Unit tests
        run: yarn test --colors

  build:
    name: Build Docker image & save to artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t stockdog:pr-${{ github.event.number }} .

      - name: Save Docker image to artifact
        if: success() && github.event_name == 'pull_request'
        run: docker save stockdog:pr-${{ github.event.number }} > stockdog-pr-${{ github.event.number }}.image.tar

      - name: Upload Docker image to artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: stockdog-pr-${{ github.event.number }}.image.tar

  push:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Docker image from artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker image
        run: |
          docker load < stockdog-pr-${{ github.event.number }}.image.tar
          docker tag stockdog:pr-${{ github.event.number }} stockdog:alpha-${{ github.event.number }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/stockdog:alpha-${{ github.event.number }}

      - name: Update image metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/stockdog:alpha-${{ github.event.number }}
          tags: |
            type=sha
          labels: |
            org.opencontainers.image.title=StockDog App
            org.opencontainers.image.description=Stock market analysis app
            org.opencontainers.image.url=https://github.com/${{github.repository}}
            org.opencontainers.image.revision=${{github.sha}}
            org.opencontainers.image.licenses=MIT
